FROM feiteng.harbor.ctyun.cn:5000/feitengky10/golang:1.15.6

ADD .   /go/src/github.com/goharbor/harbor-scanner-clair/
WORKDIR /go/src/github.com/goharbor/harbor-scanner-clair/

RUN export GOFLAGS=-mod=vendor GOOS=linux GO111MODULE=on CGO_ENABLED=0 && \
	go build -o harbor-scanner-clair cmd/harbor-scanner-clair/main.go
