FROM feiteng.harbor.ctyun.cn:5000/feitengky10/golang:1.15.6

ADD .   /go/src/github.com/quay/clair/
WORKDIR /go/src/github.com/quay/clair/

RUN export CLAIR_VERSION=$(git describe --tag --always --dirty) GO111MODULE=on && \
	go build -ldflags "-X github.com/quay/clair/pkg/version.Version=$CLAIR_VERSION" ./cmd/clair
